export const boardData =  
[
    {
        id: 0,
        name: "GO",
        go: true,
        gridRow: '12/14',
        gridColumn: '1/3',
    },
    {
        id: 1,
        name : "Old Kent Rd",
        color : "brown",
        price : 600,
        base: 20,
        hcost: 500,
        houses : 0,
        hotels : 0,
        setSize: 2,
        setPairIndices: [3],
        owned : false,
        owner : null,
        property : true,
        gridRow: '11',
        gridColumn: '1/3',
        mortgaged: false,
    },
    {
        id: 2,
        name: "Community",
        comm: true,
        gridRow: 10,
        gridColumn: '1/3',
    },
    {
        id: 3,
        name : "Whitechapel Rd",
        color : "brown",
        price : 600,
        base: 20,
        hcost: 500,
        houses : 0,
        hotels : 0,
        setSize: 2,
        setPairIndices: [1],
        owned : false,
        owner : null,
        property : true,
        gridRow: '9',
        gridColumn: '1/3',
        mortgaged: false,
    },
    {
        id: 4,
        name: "Income Tax",
        tax: true,
        amt: 2000,
        // property: false,
        gridRow: '8',
        gridColumn: '1/3',
    },
    {
        id: 5,
        name: "King Cross Stn",
        // color : "black",
        price: 2000,
        base: 250,
        station: true,
        setSize: 4,
        setPairIndices: [15, 25, 35],
        owned : false,
        owner : null,
        property : true,
        gridRow: '7',
        gridColumn: '1/3',
        mortgaged: false,
    },
    {
        id: 6,
        name : "The Angel Isl'n",
        color : "lightskyblue",
        price : 1000,
        base: 60,
        hcost: 500,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [8, 9],
        owned : false,
        owner : null,
        property : true,
        gridRow: '6',
        gridColumn: '1/3',
        mortgaged: false,
    },
    {
        id: 7,
        name: "Chance",
        chance: true,
        // property : false,
        gridRow: '5',
        gridColumn: '1/3',
    },
    {
        id: 8,
        name : "Euston Rd",
        color : "lightskyblue",
        price : 1000,
        base: 60,
        hcost: 500,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [6, 9],
        owned : false,
        owner : null,
        property : true,
        gridRow: '4',
        gridColumn: '1/3',
        mortgaged: false,
    },
    {
        id: 9,
        name : "Pentonville Rd",
        color : "lightskyblue",
        price : 1200,
        base: 80,
        hcost: 500,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [6, 8],
        owned : false,
        owner : null,
        property : true,
        gridRow: '3',
        gridColumn: '1/3',
        mortgaged: false,
    },
    {
        id: 10,
        name : "Visiting Jail",
        pass: true,
        gridRow: '1/3',
        gridColumn: '1/3',
    },
    {
        id: 11,
        name : "Pall Mall",
        color : "hotpink",
        price : 1400,
        base: 100,
        hcost: 1000,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [13, 14],
        owned : false,
        owner : null,
        property : true,
        gridRow: '1/3',
        gridColumn: '3',
        mortgaged: false,
    },
    {
        id: 12,
        name : "Electrics",
        // color: "z",
        base: 4,
        price : 1500,
        setSize: 2,
        setPairIndices: [28],
        owned : false,
        owner : null,
        utility : true,
        gridRow: '1/3',
        gridColumn: '4',
        mortgaged: false,
    },
    {
        id: 13,
        name : "Whitehall",
        color : "hotpink",
        price : 1400,
        base: 100,
        hcost: 1000,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [11, 14],
        owned : false,
        owner : null,
        property : true,
        gridRow: '1/3',
        gridColumn: 5,
        mortgaged: false,
    },
    {
        id: 14,
        name : "Northumb'd",
        color : "hotpink",
        price : 1600,
        base: 120,
        hcost: 1000,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [11, 13],
        owned : false,
        owner : null,
        property : true,
        gridRow: '1/3',
        gridColumn: '6',
        mortgaged: false,
    },
    {
        id: 15,
        name: "Marleybone Stn",
        // color : "black",
        price: 2000,
        base: 250,
        station: true,
        setSize: 4,
        setPairIndices: [5, 25, 35],
        property : true,
        owned : false,
        owner : null,
        gridRow: '1/3',
        gridColumn: '7',
        mortgaged: false,
    },
    {
        id: 16,
        name : "Bow St",
        color : "orange",
        price : 1800,
        base: 140,
        hcost: 1000,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [18, 19],
        owned : false,
        owner : null,
        property : true,
        gridRow: '1/3',
        gridColumn: '8',
        mortgaged: false,
    },
    {
        id: 17,
        name: "Community",
        comm: true,
        gridRow: '1/3',
        gridColumn: '9',
    },
    {
        id: 18,
        name : "Marlborough St",
        color : "orange",
        price : 1800,
        base: 140,
        hcost: 1000,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [16, 19],
        owned : false,
        owner : null,
        property : true,
        gridRow: '1/3',
        gridColumn: '10',
        mortgaged: false,
    },
    {
        id: 19,
        name : "Vine St",
        color : "orange",
        price : 2000,
        base: 160,
        hcost: 1500,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [16, 18],
        owned : false,
        owner : null,
        property : true,
        gridRow: '1/3',
        gridColumn: '11',
        mortgaged: false,
    },
    {
        id: 20,
        name : "Free Parking",
        free: true,
        gridRow: '1/3',
        gridColumn: "12/14",
    },
    {
        id: 21,
        name : "Strand",
        color : "red",
        price : 2200,
        base: 180,
        hcost: 1000,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [23, 24],
        owned : false,
        owner : null,
        property : true,
        gridRow: '3',
        gridColumn: "12/14",
        mortgaged: false,
    },
    {
        id: 22,
        name : "Chance",
        chance : true,
        gridRow: 4,
        gridColumn: "12/14",
    },
    {
        id: 23,
        name : "Fleet St",
        color : "red",
        price : 2200,
        base: 180,
        hcost: 1500,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [21, 24],
        owned : false,
        owner : null,
        property : true,
        gridRow: '5',
        gridColumn: "12/14",
        mortgaged: false,
    },
    {
        id: 24,
        name : "Trafalgar Sq",
        color : "red",
        price : 2400,
        base: 200,
        hcost: 1500,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [21, 23],
        owned : false,
        owner : null,
        property : true,
        gridRow: '6',
        gridColumn: "12/14",
        mortgaged: false,
    },
    {
        id: 25,
        name: "Fenchurch Stn",
        // color : "black",
        price: 2000,
        base: 250,
        station: true,
        setSize: 4,
        setPairIndices: [5, 15, 35],
        property : true,
        owned : false,
        owner : null,
        gridRow: '7',
        gridColumn: "12/14",
        mortgaged: false,
    },
    {
        id: 26,
        name : "Leicester Sq",
        color : "yellow",
        price : 2600,
        base: 220,
        hcost: 1500,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [27, 29],
        owned : false,
        owner : null,
        property : true,
        gridRow: '8',
        gridColumn: "12/14",
        mortgaged: false,
    },
    {
        id: 27,
        name : "Coventry St",
        color : "yellow",
        price : 2600,
        base: 220,
        hcost: 1500,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [26, 29],
        owned : false,
        owner : null,
        property : true,
        gridRow: '9',
        gridColumn: "12/14",
        mortgaged: false,
    },
    {
        id: 28,
        name: "Water Works",
        setSize: 2,
        setPairIndices: [12],
        // color: "z",
        base: 4,
        price : 1500,
        utility : true,
        gridRow: '10',
        gridColumn: "12/14",
        mortgaged: false,
    },
    {
        id: 29,
        name : "Picadilly",
        color : "yellow",
        price : 2800,
        base: 240,
        hcost: 1500,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [26, 27],
        owned : false,
        owner : null,
        property : true,
        gridRow: '11',
        gridColumn: "12/14",
        mortgaged: false,
    },
    {
        id: 30,
        name: "Go To Jail",
        jail: true,
        gridRow: "12/14",
        gridColumn: "12/14",
    },
    {
        id: 31,
        name : "Regent St",
        color : "darkgreen",
        price : 3000,
        base: 260,
        hcost: 2000,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [32, 34],
        owned : false,
        owner : null,
        property : true,
        gridRow: "12/14",
        gridColumn: '11',
        mortgaged: false,
    },
    {
        id: 32,
        name : "Oxford St",
        color : "darkgreen",
        price : 3000,
        base: 260,
        hcost: 2000,
        houses : 0,
        hotels : 0,
        setSize: 3,
        owned : false,
        owner : null,
        property : true,
        gridRow: "12/14",
        gridColumn: '10',
        mortgaged: false,
    },
    {
        id: 33,
        name: "Community",
        comm: true,
        gridRow: "12/14",
        gridColumn: '9',
    },
    {
        id: 34,
        name : "Bond St",
        color : "darkgreen",
        price : 3200,
        base: 280,
        hcost: 2000,
        houses : 0,
        hotels : 0,
        setSize: 3,
        setPairIndices: [31, 32],
        owned : false,
        owner : null,
        property : true,
        gridRow: "12/14",
        gridColumn: '8',
        mortgaged: false,
    },
    {
        id: 35,
        name: "Liverpool Stn",
        // color : "black",
        price: 2000,
        base: 250,
        station: true,
        setSize: 4,
        setPairIndices: [5, 15, 25],
        property : true,
        owned : false,
        owner : null,
        gridRow: "12/14",
        gridColumn: '7',
        mortgaged: false,
    },
    {
        id: 36,
        name: "Chance",
        chance: true,
        gridRow: "12/14",
        gridColumn: '6',
    },
    {
        id: 37,
        name : "Park Lane",
        color : "darkblue",
        price : 3500,
        base: 350,
        hcost: 2000,
        houses : 0,
        hotels : 0,
        setSize: 2,
        setPairIndices: [39],
        owned : false,
        owner : null,
        property : true,
        gridRow: "12/14",
        gridColumn: '5',
        mortgaged: false,
    },
    {
        id: 38,
        name: "Super Tax",
        tax: true,
        amt: 1000,
        gridRow: "12/14",
        gridColumn: '4',
    },
    {
        id: 39,
        name : "Mayfair",
        color : "darkblue",
        price : 4000,
        base: 500,
        hcost: 2000,
        houses : 0,
        hotels : 0,
        setSize: 2,
        setPairIndices: [39],
        owned : false,
        owner : null,
        property : true,
        gridRow: "12/14",
        gridColumn: '3',
        mortgaged: false,
    },
];
export const chanceCards = [
    {
        id: 0,
        desc: "Take a helicopter ride to Mayfair",
        action: "move",
        destination: 39,
    },
    {
        id: 1,
        desc: "Collect $150",
        action: "add",
        amt: 150,
    },
    {
        id: 2,
        desc: "Pay $50",
        action: "pay",
        amt: 50,
    },
];
export const communityCards = [
    {
        id: 0,
        desc: "Take a helicopter ride to Mayfair",
        action: "move",
        destination: 39,
    },
    {
        id: 1,
        desc: "Collect $150",
        action: "add",
        amt: 150,
    },
    {
        id: 2,
        desc: "Pay $50",
        action: "pay",
        amt: 50,
    },
];
